const mongoose = require('mongoose');

const StudentSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  role: { type: String, enum: ['admin', 'teacher', 'student'], default: 'student' },
  
  // University specific identifiers
  prnNumber: { type: String, required: true, unique: true }, 
  branch: { type: String, enum: ['Mechatronics', 'Computer', 'Civil', 'Mechanical', 'Electrical'], required: true },
  year: { type: Number, required: true }, // e.g., 1 for First Year
  
  // For the Python WhatsApp Alert Microservice
  parentPhone: { type: String, required: true }, 
  
  // Security: The persistent hash generated by FingerprintJS on their phone
  registeredDeviceId: { type: String }, 
  
  // References to the classes this student is enrolled in
  enrolledClasses: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Class' }]
}, { timestamps: true });

// Indexes for performance
StudentSchema.index({ email: 1 });
StudentSchema.index({ prnNumber: 1 });
StudentSchema.index({ role: 1 });
StudentSchema.index({ branch: 1, year: 1 });

module.exports = mongoose.model('Student', StudentSchema);